// Maps team name to flag-icons ISO code
export const TEAM_FLAGS = {
  'Mexico': 'mx',
  'South Africa': 'za',
  'Korea Republic': 'kr',
  'Czechia': 'cz',
  'Canada': 'ca',
  'Bosnia-Herzegovina': 'ba',
  'USA': 'us',
  'Paraguay': 'py',
  'Qatar': 'qa',
  'Switzerland': 'ch',
  'Brazil': 'br',
  'Morocco': 'ma',
  'Haiti': 'ht',
  'Scotland': 'gb-sct',
  'Australia': 'au',
  'Turkey': 'tr',
  'Germany': 'de',
  'Curaçao': 'cw',
  'Netherlands': 'nl',
  'Japan': 'jp',
  "Côte d'Ivoire": 'ci',
  'Ecuador': 'ec',
  'Sweden': 'se',
  'Tunisia': 'tn',
  'Spain': 'es',
  'Cabo Verde': 'cv',
  'Belgium': 'be',
  'Egypt': 'eg',
  'Saudi Arabia': 'sa',
  'Uruguay': 'uy',
  'IR Iran': 'ir',
  'New Zealand': 'nz',
  'France': 'fr',
  'Senegal': 'sn',
  'Iraq': 'iq',
  'Norway': 'no',
  'Argentina': 'ar',
  'Algeria': 'dz',
  'Austria': 'at',
  'Jordan': 'jo',
  'Portugal': 'pt',
  'Congo DR': 'cd',
  'England': 'gb-eng',
  'Croatia': 'hr',
  'Ghana': 'gh',
  'Panama': 'pa',
  'Uzbekistan': 'uz',
  'Colombia': 'co',
};

export const getFlagCode = (teamName) => TEAM_FLAGS[teamName] || null;
